Repository octokit/auth-action.js, pull requests merged in 2022-07, with the labels that each got.

#221 ci: stop testing against NodeJS v10, v12
  .github/workflows/test.yml
  package.json
Labels: blocked, maintenance

#226 ci(test): use text_matrix and test jobs
  .github/workflows/test.yml
Labels: maintenance

#229 [deps] updates pika/pack to a non vulnerable version
  package-lock.json
  package.json
Labels: dependencies, maintenance
